version: "3"
services:
  cloudsql:
    command:
      [
        "/cloud_sql_proxy",
        "-instances=upbeat-glow-336702:asia-northeast1:postgres-instance=tcp:0.0.0.0:5432",
        "-credential_file=/config",
      ]
    image: asia.gcr.io/cloudsql-docker/gce-proxy
    ports:
      - "5432:5432"
    volumes:
      - ./credentials.json:/config
